import { ArrowDownRight, ArrowUpRight, Leaf, Star } from 'lucide-react'
import { Link } from 'react-router-dom'
import ProductCard from '../components/ProductCard'
import { products } from '../data/products'

function Home({ onAdd, onWishlistToggle, isInWishlist }) {
  return <><section className="hero"><div className="hero-copy"><p className="eyebrow">SKIN, SIMPLIFIED</p><h1>Good skin begins with a quiet ritual.</h1><p className="hero-text">Thoughtful formulas for the everyday moments that make you feel more like yourself.</p><Link className="primary-button" to="/shop">Explore the collection <ArrowUpRight size={15} /></Link></div><div className="hero-art"><img src="/images/skincare-collection.png" alt="BeautyCart skincare products on a warm stone surface" /><div className="hero-note"><span>01</span><p>Formulated for your everyday.</p></div></div></section><section className="intro-strip"><div><Leaf size={20} /><p>Made with intention</p></div><div><Star size={20} /><p>4.8 average ritual rating</p></div><div><ArrowDownRight size={20} /><p>Less, but better</p></div></section><section className="collection"><div className="section-heading"><div><p className="eyebrow">THE EDIT</p><h2>Daily essentials</h2></div><Link to="/shop">View all products <ArrowUpRight size={14} /></Link></div><div className="product-grid">{products.slice(0, 3).map((product) => <ProductCard key={product.id} product={product} onAdd={onAdd} onWishlistToggle={onWishlistToggle} isInWishlist={isInWishlist} />)}</div></section><section className="editorial"><div className="editorial-image"><img src="/images/editorial-ritual.png" alt="A calm skincare ritual with cream, serum, linen, and olive leaves" /></div><div className="editorial-copy"><p className="eyebrow">THE BEAUTYCART METHOD</p><h2>Small rituals.<br />Real results.</h2><p>We believe good skincare should meet you where you are. Our edit is intentionally small, sensory, and easy to return to every day.</p><Link className="text-link" to="/about">Read our philosophy <ArrowUpRight size={14} /></Link></div></section><section className="ritual-banner"><p className="eyebrow">A LITTLE MORE INTENTION</p><h2>Make space for the ritual.</h2><p>Small-batch care, uncomplicated routines, and ingredients your skin understands.</p></section></>
}

export default Home
